=== muruganantham-d/E-Commerce-Microservices-Architecture/ecommerce-microservices/packages/contracts/events/schemas/product.created.v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://ecom.contracts/events/product.created.v1.schema.json",
  "title": "product.created.v1",
  "type": "object",
  "additionalProperties": false,
  "required": ["eventId", "eventType", "timestamp", "version", "source", "payload"],
  "properties": {
    "eventId": { "type": "string", "format": "uuid" },
    "eventType": { "const": "product.created" },
    "timestamp": { "type": "string", "format": "date-time" },
    "version": { "const": "v1" },
    "source": { "const": "product-service" },
    "payload": {
      "type": "object",
      "additionalProperties": false,
      "required": ["productId", "sku", "name", "price", "currency", "isActive", "createdAt"],
      "properties": {
        "productId": { "type": "string" },
        "sku": { "type": "string" },
        "name": { "type": "string" },
        "price": { "type": "number", "minimum": 0 },
        "currency": { "type": "string", "minLength": 3, "maxLength": 3 },
        "isActive": { "type": "boolean" },
        "createdAt": { "type": "string", "format": "date-time" }
      }
    }
  },
  "examples": [
    {
      "eventId": "68c4d307-6e12-4f9b-8a87-5856a8ec2e3f",
      "eventType": "product.created",
      "timestamp": "2026-02-16T10:22:00.000Z",
      "version": "v1",
      "source": "product-service",
      "payload": {
        "productId": "prd_2001",
        "sku": "SKU-2001",
        "name": "Wireless Mouse",
        "price": 29.99,
        "currency": "USD",
        "isActive": true,
        "createdAt": "2026-02-16T10:21:59.000Z"
      }
    }
  ]
}

=== muruganantham-d/E-Commerce-Microservices-Architecture/ecommerce-microservices/packages/contracts/events/examples/product.created.v1.json
{
  "eventId": "68c4d307-6e12-4f9b-8a87-5856a8ec2e3f",
  "eventType": "product.created",
  "timestamp": "2026-02-16T10:22:00.000Z",
  "version": "v1",
  "source": "product-service",
  "payload": {
    "productId": "prd_2001",
    "sku": "SKU-2001",
    "name": "Wireless Mouse",
    "price": 29.99,
    "currency": "USD",
    "isActive": true,
    "createdAt": "2026-02-16T10:21:59.000Z"
  }
}
